//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelDepartment.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Personnel
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Department Name")]
        public Nullable<int> DepartmentId { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Surname { get; set; }
        [Required]
        [Display(Name ="Date Of Birth")]
        public Nullable<System.DateTime> Date_of_Birth { get; set; }
        [Required]
        public Nullable<bool> Gender { get; set; }
        [Required]
        public Nullable<bool> Married { get; set; }
        [Required]
        [Range(2020,10000)]
        public Nullable<double> Salary { get; set; }
       

        public virtual Department Department { get; set; }
    }
}
